
name: Coverage

on:
  workflow_call:


jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
            submodules: recursive
            ref: main
      - name: Install deps
        run: sudo apt-get install lcov
      - name: Run tests on main for coverage comparison
        run: |
          git checkout main
          cmake -Bbuild && cd build
          cmake --build .
          make test
          cp build/coverage.info /tmp/coverage_main.info
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Run tests on main for coverage comparison
        run: |
          git checkout main
          cmake -Bbuild && cd build
          cmake --build .
          make test
      - name: Coverage
        uses: romeovs/lcov-reporter-action@2a28ec3e25fb7eae9cb537e9141603486f810d1a
        with:
          lcov-base: /tmp/coverage_main.info
          lcov-file: build/coverage.info
          delete-old-comments: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload coverage artifact
        uses: actions/upload-artifact@master
        with:
          name: coverage-html
          path: build/coverage/