
name: Coverage

on:
  workflow_call:


jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
            submodules: recursive
            ref: main
      - name: Install deps
        run: sudo apt-get install lcov
      - name: Run tests on main for coverage comparison
        run: |
          git checkout main
          cmake -Bbuild-main && cd build-main
          cmake --build .
          make test
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Run tests on main for coverage comparison
        run: |
          git checkout main
          cmake -Bbuild && cd build
          cmake --build .
          make test
      - name: Coverage
        uses: romeovs/lcov-reporter-action@2a28ec3e25fb7eae9cb537e9141603486f810d1a
        with:
          lcov-base: build-main/coverage.info
          lcov-file: build/coverage.info
          delete-old-comments: true
          github-token: ${{ secrets.GITHUB_TOKEN }}