name: "Federated templates"

on:
  pull_request:
  
jobs:
  ci:
    name: Build federated templates
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup java and gradle for compiling lfc
        uses: ./.github/actions/lingua-franca

      - name: Build federated templates example
        working-directory: ${{ github.workspace }}/examples/fed-template
        run: |
          source ${{github.workspace}}/env.bash
          ./buildAll.sh
        shell: bash
      
