name: Memory usage report

on:
  push:
    branches:
      - main
  pull_request:
  
permissions:
  contents: read

jobs:
  ci:
    name: Report memory usage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Test
        run:
          make test
      - name: Combine
        # TODO: Also add name of each test to the report itself
        run:
          cat build/test/*.size > build/report.txt
      - name: Report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: build/report.txt
      - name: Comment
        uses: live-codes/pr-comment-from-artifact@v1.0.1
        with:
          artifact: report
  
