name: Memory usage report

on:
  pull_request:
  
permissions:
  contents: write
  pull-requests: write

jobs:
  ci:
    name: Report memory usage
    runs-on: ubuntu-latest
    steps:
      # To get the potential changes to CI
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Generate memory usage report (current branch)
        id: head
        uses: ./.github/actions/memory-report
        with:
          branch: ${{ github.head_ref }}
      - name: Generate memory usage report (target branch)
        id: base
        uses: ./.github/actions/memory-report
        with:
          branch: ${{ github.base_ref }}
      
      # To get back to the PR branch
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Compare
        run: |
          echo "$BASE_REPORT" > base_report.txt
          echo "$HEAD_REPORT" > head_report.txt
          python3 -m pip install -r scripts/ci/reports/requirements.txt
          python3 scripts/ci/reports/parse-reports.py \
                  base_report.txt \
                  head_report.txt \
                  report
        env:
          BASE_REPORT: ${{ steps.base.outputs.report }}
          HEAD_REPORT: ${{ steps.head.outputs.report }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Base reports
          path: base_report.txt
      - name: Comment memory usage tables
        uses: GrantBirki/comment@v2.1.0
        with:
          file: report.md
